### ISSUE TITLE
Issue with `variables/local.env.example`

### ISSUE THREAD

**Issue by jeremi** [TrafficGuard/nous#19]
in https://github.com/TrafficGuard/nous/blob/main/variables/local.env.example#L38 the `=` is missing after `FIREWORKS_KEY`

and:
> JIRA_BASE_URL=https://<accountName>.atlassian.net/rest/api/latest/

should be:

> JIRA_BASE_URL="https://<accountName>.atlassian.net/rest/api/latest/"

so it does not break.

**Comment by danielcampagnolitg** [comment]
Thanks for reporting that. Fixed.
