### ISSUE TITLE
setup error localy

### ISSUE THREAD

**Issue by kabani7** [TrafficGuard/nous#24]
I am getting this error when I run the frontend start 

![image](https://github.com/user-attachments/assets/1e4f3b40-a5cc-4c33-a3d0-98ac3c08fce2)

**Comment by danielcampagnolitg** [comment]
Hi, which OS shell are you running this from?

**Comment by kabani7** [comment]
Windows

**Comment by danielcampagnolitg** [comment]
You'll need to run it through docker on Windows.  It doesn't support Windows directly
